# prefix will be prepended to all resource names
variable "prefix" {
  type    = string
  default = "nodejs"
}

# Resource tag:
variable "tag_app_group" {
  type    = string
  default = "set in variables.tfvars"
}

# name of zip file to deploy, generated by 'npm pack' command
variable "zip_file_name" {
  type    = string
  default = "../dependency-postgres/postgres-dependency-8.20.0.zip"
}